name: 'Setup Python environment'
description: 'Setup Python with uv and install dependencies.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      working-directory: ./backend
      run: uv sync --locked